[unit_cell]
a = 5.64  # Lattice parameter (angstrom)
b = 5.64
c = 5.64
alpha = 90.0  # Angles (degrees)
beta = 90.0
gamma = 90.0

[atoms]
[[atoms.basis]]
element = "Na"
position = [0.0, 0.0, 0.0]  # Fractional coordinates

[[atoms.basis]]
element = "Cl"
position = [0.5, 0.5, 0.5]  # Fractional coordinates
